// @file: @/seeder/placeholder-data.ts
import { IDrink } from '@/backend/models/interfaces';
import { DrinkCategory, RetailChain, Country } from '@/backend/models/enums';
// import { RetailPrices, DrinkVolume } from '@/backend/models/types';

const beveragesData:IDrink[] = [
  {
    title: 'Wild Turkey 0.7L',
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: true,
    ratings: 5,
    country: Country.USA,
    id: 101,
  },
  {
    title: 'Wild Turkey 1.0L',
    category: DrinkCategory.Bourbon,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    id: 102,
  },
  {
    title: 'Santiago de Cuba Anejo 7',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Cuba,
    id: 103,
  },
  {
    title: 'Doorly\'s',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 104,
  },
  {
    title: 'Botafogo',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 105,
  },
  {
    title: 'Appleton',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 106,
  },
  {
    title: 'Bacardi',
    category: DrinkCategory.Rum,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 107,
  },
  {
    title: 'Ballantines',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 108,
  },
  {
    title: 'Jameson',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: true,
    ratings: 5,
    country: Country,
    id: 109,
  },
  {
    title: 'Jameson',
    category: DrinkCategory.Whiskey,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 110,
  },
  {
    title: 'Ballantines',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 111,
  },
  {
    title: 'John Walker',
    category: DrinkCategory.Whiskey,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 112,
  },
  {
    title: 'John Walker',
    category: DrinkCategory.Whiskey,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 113,
  },
  {
    title: 'Gordon\'s',
    category: DrinkCategory.Gin,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 114,
  },
  {
    title: 'Colonist',
    category: DrinkCategory.Portwein,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Ukraine,
    id: 115,
  },
  {
    title: 'Osborn',
    category: DrinkCategory.Portwein,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: true,
    ratings: 5,
    country: Country,
    id: 116,
  },
  {
    title: 'Colonist',
    category: DrinkCategory.Champagne,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country.Ukraine,
    id: 117,
  },
  {
    title: 'Martini',
    category: DrinkCategory.Champagne,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 118,
  },
  {
    title: 'Espolon',
    category: DrinkCategory.Tequila,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 119,
  },
  {
    title: 'Espolon',
    category: DrinkCategory.Tequila,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 120,
  },
  {
    title: 'Doorly\'s',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 5,
    country: Country,
    id: 121,
  },
  {
    title: 'Santiago Cuba',
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Cuba,
    id: 122,
  },
  {
    title: 'Jagermeister',
    category: DrinkCategory.Tincture,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 123,
  },
  {
    title: 'Jagermeister',
    category: DrinkCategory.Tincture,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 124,
  },
  {
    title: 'Becherovka',
    category: DrinkCategory.Tincture,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 125,
  },
  {
    title: 'Becherovka',
    category: DrinkCategory.Tincture,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 126,
  },
  {
    title: 'R.Jelinek',
    category: DrinkCategory.Tincture,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country,
    id: 127,
  },
  {
    title: 'Absolut',
    category: DrinkCategory.Horilka,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 4,
    country: Country,
    id: 128,
  },
  {
    title: 'Finlandia',
    category: DrinkCategory.Horilka,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Finland,
    id: 129,
  },
  {
    title: 'Finlandia',
    category: DrinkCategory.Horilka,
    volume: 0.5,
    prices: {
      [RetailChain.Auchan]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Novus]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.Silpo]: { price: 0, lastUpdated: new Date('2023-09-01') },
      [RetailChain.ATB]: { price: 'none', lastUpdated: new Date('2023-09-01') },
    },
    inWish: false,
    ratings: 3,
    country: Country.Finland,
    id: 130,
  },
];
