// @file: @/seeder/placeholder-data.ts


import { IDrink } from "@/backend/models/types.ts";



beveragesData:IDrink[] [
  {
    title: "Wild Turkey 0.7L",
    category: DrinkCategory.Bourbon,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: 530,
      [RetailChain.Novus]: 560,
      [RetailChain.Silpo]: 490,
      [RetailChain.ATB]: 'none',
    },
    inWish: true,
    ratings: 5,
    country: Country.USA,
    id: 101,
  },
  {
    title: "Wild Turkey 1.0L",
    category: DrinkCategory.Bourbon,
    volume: 1.0,
    prices: {
      [RetailChain.Auchan]: 480,
      [RetailChain.Novus]: 510,
      [RetailChain.Silpo]: 'none',
      [RetailChain.ATB]: 460,
    },
    inWish: false,
    ratings: 5,
    country: Country.USA,
    id: 102,
  },
  {
    title: "Santiago de Cuba Anejo 7",
    category: DrinkCategory.Rum,
    volume: 0.7,
    prices: {
      [RetailChain.Auchan]: 480,
      [RetailChain.Novus]: 510,
      [RetailChain.Silpo]: 'none',
      [RetailChain.ATB]: 460,
    },
    inWish: false,
    ratings: 3,
    country: Country.Cuba,
    id: 103,
  },
  {
    title: "Doorly's",
    category: "amber rum",
    volume: "0.7L",
    price: 725,
    inWish: false,
    ratings: false,
    id: 104,
  },
  {
    title: "Botafogo",
    category: "amber rum",
    volume: "0.7L",
    price: 700,
    inWish: false,
    ratings: false,
    id: 105,
  },
  {
    title: "Appleton",
    category: "amber rum",
    volume: "0.7L",
    price: 645,
    inWish: false,
    ratings: false,
    id: 106,
  },
  {
    title: "Bacardi",
    category: "amber rum",
    volume: "0.5L",
    price: 260,
    inWish: false,
    ratings: false,
    id: 107,
  },
  {
    title: "Ballantines",
    category: "whiskey Lime",
    volume: "0.7L",
    price: 550,
    inWish: false,
    ratings: false,
    id: 108,
  },
  {
    title: "Jameson",
    category: "whiskey",
    volume: "0.7L",
    price: 500,
    inWish: true,
    ratings: false,
    id: 109,
  },
  {
    title: "Jameson",
    category: "whiskey",
    volume: "0.5L",
    price: 470,
    inWish: false,
    ratings: false,
    id: 110,
  },
  {
    title: "Ballantines",
    category: "whiskey",
    volume: "0.7L",
    price: 490,
    inWish: false,
    ratings: false,
    id: 111,
  },
  {
    title: "John Walker",
    category: "whiskey",
    volume: "0.7L",
    price: 430,
    inWish: false,
    ratings: false,
    id: 112,
  },
  {
    title: "John Walker",
    category: "whiskey",
    volume: "0.5L",
    price: 350,
    inWish: false,
    ratings: false,
    id: 113,
  },
  {
    title: "Gordon's",
    category: "gin",
    volume: "0.7L",
    price: 450,
    inWish: false,
    ratings: false,
    id: 114,
  },
  {
    title: "Colonist",
    category: "portwein",
    volume: "0.7L",
    price: 510,
    inWish: false,
    ratings: true,
    id: 115,
  },
  {
    title: "Osborn",
    category: "portwein",
    volume: "0.7L",
    price: 300,
    inWish: true,
    ratings: false,
    id: 116,
  },
  {
    title: "Colonist",
    category: "champagne brut",
    volume: "0.7L",
    price: 360,
    inWish: false,
    ratings: false,
    id: 117,
  },
  {
    title: "Martini",
    category: "champagne brut",
    volume: "0.7L",
    price: 245,
    inWish: false,
    ratings: false,
    id: 118,
  },
  {
    title: "Espolon",
    category: "yellow tequila",
    volume: "0.7L",
    price: 990,
    inWish: false,
    ratings: false,
    id: 119,
  },
  {
    title: "Espolon",
    category: "white tequila",
    volume: "0.7L",
    price: 860,
    inWish: false,
    ratings: false,
    id: 120,
  },
  {
    title: "Doorly's",
    category: "white rum",
    volume: "0.7L",
    price: 645,
    inWish: false,
    ratings: false,
    id: 121,
  },
  {
    title: "Santiago Cuba",
    category: "white rum",
    volume: "0.7L",
    price: 420,
    inWish: false,
    ratings: false,
    id: 122,
  },
  {
    title: "Jagermeister",
    category: "tincture",
    volume: "0.7L",
    price: 460,
    inWish: false,
    ratings: false,
    id: 123,
  },
  {
    title: "Jagermeister",
    category: "tincture",
    volume: "1.0L",
    price: 600,
    inWish: false,
    ratings: false,
    id: 124,
  },
  {
    title: "Becherovka",
    category: "tincture",
    volume: "0.7L",
    price: 360,
    inWish: false,
    ratings: false,
    id: 125,
  },
  {
    title: "Becherovka",
    category: "tincture",
    volume: "0.5L",
    price: 250,
    inWish: false,
    ratings: false,
    id: 126,
  },
  {
    title: "R.Jelinek",
    category: "tincture",
    volume: "0.5L",
    price: 200,
    inWish: false,
    ratings: false,
    id: 127,
  },
  {
    title: "Absolut",
    category: "horilka",
    volume: "0.7L",
    price: 320,
    inWish: false,
    ratings: false,
    id: 128,
  },
  {
    title: "Finlandia",
    category: "horilka",
    volume: "0.7L",
    price: 300,
    inWish: false,
    ratings: false,
    id: 129,
  },
  {
    title: "Finlandia",
    category: "horilka",
    volume: "0.5L",
    price: 290,
    inWish: false,
    ratings: false,
    id: 130,
  },
];
