// @/models/enums.ts

export enum RetailChain {
  Auchan = 'Auchan',
  Novus = 'Novus',
  Silpo = 'Silpo',
  ATB = 'ATB',
}

export enum Country {
  Argentina = 'Argentina',
  Australia = 'Australia',
  Barbados = 'Barbados',
  Belgium = 'Belgium',
  Britain = 'Britain',
  Bulgaria = 'Bulgaria',
  Cuba = 'Cuba',
  CzechRepublic = 'Czech Republic',
  Finland = 'Finland',
  France = 'France',
  Germany = 'Germany',
  Greece = 'Greece',
  Ireland = 'Ireland',
  Italy = 'Italy',
  Jamaica = 'Jamaica',
  Mexico = 'Mexico',
  Poland = 'Poland',
  Scotland = 'Scotland',
  Slovakia = 'Slovakia',
  SouthAfrica = 'South Africa',
  Spain = 'Spain',
  Sweden = 'Sweden',
  Ukraine = 'Ukraine',
  USA = 'USA',
}

export enum DrinkCategory {
  Bourbon = 'bourbon',
  Champagne = 'champagne',
  Gin = 'gin',
  Horilka = 'horilka',
  Portwein = 'portwein',
  Rum = 'rum',
  Tequila = 'tequila',
  Tincture = 'tincture',
  Whiskey = 'whiskey',
  Wine = 'wine'
}

export enum CocktailIngredients {
  ANGOSTURA_BITTERS = 'Angostura Bitters',
  BLACK_PEPPER = 'Black Pepper',
  BLUE_CURACAO = 'Blue Curacao',
  CAMPARI = 'Campari',
  COCONUT_CREAM = 'Coconaut Cream',
  COINTREAU = 'Cointreau',
  CRANBERRY_JUICE = 'Cranberry Juice',
  GRENADINE_SYRUP = 'Grenadine Syrup',
  CRUSHED_ICE = 'Crushed Ice',
  GIN = 'Gin',
  HORILKA = 'horilka',
  ICE_CUBES = 'Ice Cubes',
  LEMON_JUICE = 'Lemon Juice',
  LIME_JUICE = 'Lime Juice',
  ORANGE_JUICE = 'Orange Juice',
  PEACH_SCHNAPPS = 'Peach Schnapps',
  PINEAPPLE_JUICE = 'Pineapple Juice',
  RUM = 'Rum',
  CHAMPAGNE = 'Champagne',
  SIMPLE_SYRUP = 'Simple Syrup',
  SODA_WATER = 'Soda Water',
  SPRITE = 'Sprite',
  SWEET_AND_SOUR_MIX = 'Sweet and Sour Mix',
  TEQUILA = 'Tequila',
  TOMATO_JUICE = 'Tomato Juice',
  TRIPLE_SEC = 'Triple Sec',
  VERMOUTH = 'Vermouth',
  WHITE_RUM = 'White Rum',
  WHISKEY = 'Whiskey',
  WORCESTERSHIRE_SAUCE = 'Worcestershire Sauce',
}

export enum GlassType {
  COCKTAIL = 'Cocktail',
  COLLINS = 'Collins',
  COUPE = 'Coupe',
  HIGHBALL = 'Highball',
  HURRICANE = 'Hurricane',
  MARGARITA = 'Margarita',
  MARTINI = 'Martini',
  OLD_FASHIONED = 'Old Fashioned',
  PINT = 'Pint',
  ROCKS = 'Rocks',
  SNIFTER = 'Snifter',
  SHOT = 'Shot',
  WINE = 'Wine',
}