// @/models/enums.ts

export enum RetailChain {
  Auchan = 'Auchan',
  Novus = 'Novus',
  Silpo = 'Silpo',
  ATB = 'ATB',
}

export enum Country {
  Argentina = 'Argentina',
  Australia = 'Australia',
  Barbados = 'Barbados',
  Belgium = 'Belgium',
  Britain = 'Britain',
  Bulgaria = 'Bulgaria',
  Cuba = 'Cuba',
  CzechRepublic = 'Czech Republic',
  Finland = 'Finland',
  France = 'France',
  Germany = 'Germany',
  Greece = 'Greece',
  Ireland = 'Ireland',
  Italy = 'Italy',
  Jamaica = 'Jamaica',
  Mexico = 'Mexico',
  Poland = 'Poland',
  Scotland = 'Scotland',
  Slovakia = 'Slovakia',
  SouthAfrica = 'South Africa',
  Spain = 'Spain',
  Sweden = 'Sweden',
  Ukraine = 'Ukraine',
  USA = 'USA',
}

export enum DrinkCategory {
  Bourbon = 'bourbon',
  Champagne = 'champagne',
  Gin = 'gin',
  Horilka = 'horilka',
  Portwein = 'portwein',
  Rum = 'rum',
  Tequila = 'tequila',
  Tincture = 'tincture',
  Whiskey = 'whiskey',
  Wine = 'wine'
}

export enum CocktailIngredients {
  ABSINTHE = 'Absinthe',
  ANGOSTURA_BITTERS = 'Angostura Bitters',
  ANGOSTURA_SUGAR = 'Angostura Sugar',
  BLACK_PEPPER = 'Black Pepper',
  BLUE_CURACAO = 'Blue Curacao',
  BOURBON = 'Bourbon',
  CAMPARI = 'Campari',
  CHAMPAGNE = 'Champagne',
  COCA_COLA = 'Coca Cola',
  COINTREAU = 'Cointreau',
  COCONUT_CREAM = 'Coconaut Cream',
  COCONUT_LIQUEUR = 'Coconaut Liqueur',
  CRANBERRY_JUICE = 'Cranberry Juice',
  EGG_WHITE = 'Egg White',
  GRAPEFRUIT_JUICE = 'Grapefruit Juice',
  GRENADINE_SYRUP = 'Grenadine Syrup',
  CRUSHED_ICE = 'Crushed Ice',
  GIN = 'Gin',
  HORILKA = 'horilka',
  ICE_CUBES = 'Ice Cubes',
  IRISH_CREAM_LIQUEUR = 'Irish cream liqueur',
  LEMON_JUICE = 'Lemon Juice',
  LIME_JUICE = 'Lime Juice',
  LIME_WEDGES = 'Lime Wedges',
  MINT_LEAVES = 'Mint Leaves',
  ORANGE_JUICE = 'Orange Juice',
  ORGEAT_SYRUP = 'Orgeat Syrup',
  PEACH_SCHNAPPS = 'Peach Schnapps',
  PINEAPPLE_JUICE = 'Pineapple Juice',
  RASPBERRY_PUREE = 'Raspberry puree',
  RUM_DARK = 'Dark Rum',
  RUM_WHITE = 'White Rum',
  SALT = 'Salt',
  SAMBUCA = 'Sambuca',
  SIMPLE_SYRUP = 'Simple Syrup',
  SODA_WATER = 'Soda Water',
  SPARKLING_WATER = 'Sparkling Water',
  SPRITE = 'Sprite',
  STRAWBERRY_PUREE = 'Strawberry puree',
  SUGAR_SYRUP = 'Sugar Syrup',
  SWEET_AND_SOUR_MIX = 'Sweet and Sour Mix',
  TEQUILA = 'Tequila',
  TOMATO_JUICE = 'Tomato Juice',
  TRIPLE_SEC = 'Triple Sec',
  VERMOUTH = 'Vermouth',
  WHITE_RUM = 'White Rum',
  WHISKEY = 'Whiskey',
  WORCESTERSHIRE_SAUCE = 'Worcestershire Sauce',
}

export enum GlassType {
  BODEGA = 'Bodega',
  COCKTAIL = 'Cocktail',
  COLLINS = 'Collins',
  COUPE = 'Coupe',
  GIN_GOBLET = 'Gin Goblet',
  HIGHBALL = 'Highball',
  HURRICANE = 'Hurricane',
  JULEP = 'Julep',
  MARGARITA = 'Margarita',
  MARTINI = 'Martini',
  OLD_FASHION = 'Old Fashion',
  PINT = 'Pint',
  ROCKS = 'Rocks',
  SNIFTER = 'Snifter',
  SHOT = 'Shot',
  SOUR = 'Sour',
  WINE = 'Wine',
}

export enum RecipeIngredients {
  BakingPowder = 'Baking Powder',
  Butter = 'Butter',
  Chocolate = 'Chocolate',
  Eggs = 'Eggs',
  Flour = 'Flour',
  Honey = 'Honey',
  Milk = 'Milk',
  Oil = 'Oil',
  Salt = 'Salt',
  Sugar = 'Sugar',
  VanillaExtract = 'Vanilla Extract',
  Yeast = 'Yeast',
  Beef = 'Beef',
  Chicken = 'Chicken',
  Lamb = 'Lamb',
  Pork = 'Pork',
  Turkey = 'Turkey',
  Bacon = 'Bacon',
  Sausage = 'Sausage',
  Ham = 'Ham',
  Venison = 'Venison',
  Duck = 'Duck',
}

