// https://nextjs.org/learn/dashboard-app/fetching-data
const countriesData = [
  { countryID: 101,	countryName: 'Argentina', prefixEAN: '779', },
  { countryID: 102,	countryName: 'Armenia', prefixEAN: '485', },
  { countryID: 103,	countryName: 'Australia', prefixEAN: '930', },
  { countryID: 104,	countryName: 'Barbados', prefixEAN: '500', },
  { countryID: 105,	countryName: 'Belgium', prefixEAN: '540', },
  { countryID: 106,	countryName: 'Britain', prefixEAN: '500-509', },
  { countryID: 107,	countryName: 'Bulgaria', prefixEAN: '380', },
  { countryID: 108,	countryName: 'Cuba', prefixEAN: '850', },
  { countryID: 109,	countryName: 'CzechRepublic', prefixEAN: '859', },
  { countryID: 110,	countryName: 'Dominican', prefixEAN: '746', },
  { countryID: 111,	countryName: 'Finland', prefixEAN: '640', },
  { countryID: 112,	countryName: 'France', prefixEAN: '300-379', },
  { countryID: 113,	countryName: 'Georgia', prefixEAN: '486', },
  { countryID: 114,	countryName: 'Germany', prefixEAN: '400-440', },
  { countryID: 115,	countryName: 'Greece', prefixEAN: '520', },
  { countryID: 116,	countryName: 'Ireland', prefixEAN: '539', },
  { countryID: 117,	countryName: 'Italy', prefixEAN: '800-839', },
  { countryID: 118,	countryName: 'Jamaica', prefixEAN: '600-601', },
  { countryID: 119, countryName: 'Mexico', prefixEAN: '750-751', },
  { countryID: 120,	countryName: 'Norway', prefixEAN: '700-709', },
  { countryID: 121,	countryName: 'Poland', prefixEAN: '590', },
  { countryID: 122,	countryName: 'Portugal', prefixEAN: '560', },
  { countryID: 123,	countryName: 'Scotland', prefixEAN: '500', },
  { countryID: 124,	countryName: 'Slovakia', prefixEAN: '860', },
  { countryID: 125,	countryName: 'SouthAfrica', prefixEAN: '600-601', },
  { countryID: 126,	countryName: 'Spain', prefixEAN: '841-843', },
  { countryID: 127,	countryName: 'Sweden', prefixEAN: '730-739', },
  { countryID: 128,	countryName: 'Ukraine', prefixEAN: '482', },
  { countryID: 129,	countryName: 'USA', prefixEAN: '000-019', },
];
const drinkCategoriesData = [
  { categoryID: 201, categoryName: 'absinthe' },
  { categoryID: 202, categoryName: 'bourbon' },
  { categoryID: 203, categoryName: 'brandy' },
  { categoryID: 204, categoryName: 'champagne' },
  { categoryID: 205, categoryName: 'cider' },
  { categoryID: 206, categoryName: 'gin' },
  { categoryID: 207, categoryName: 'horilka' },
  { categoryID: 208, categoryName: 'liqueur' },
  { categoryID: 209, categoryName: 'portwein' },
  { categoryID: 210, categoryName: 'rum' },
  { categoryID: 211, categoryName: 'tequila' },
  { categoryID: 212, categoryName: 'tincture' },
  { categoryID: 213, categoryName: 'whiskey' },
  { categoryID: 214, categoryName: 'wine' }
];

const beveragesData = [
  /* --- BOURBON --- */
  {
    beverageId: 1001, title: 'Wild Turkey Rare Breed 0.7L',
    category: 202, volume: 0.7,
    Auchan:1669, Novus: 0, Silpo: 2199, ATB:0, Rozetka: 1999,
    lastUpdated: '2024-01-01',
    inWish: false, ratings: 5, countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-Rare-Breed-07.webp',
    description: 'Тони паленого коричневого цукру і ванілі, трохи цитрусових, сосни і дуба.'
  },
  {
    beverageId: 1002, title: 'Wild Turkey Longbranch 0.7L',
    category: 202, volume: 0.7,
    Auchan:1637, Novus: 1779, Silpo: 1699, ATB:0, Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false, ratings: 5, countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-Longbranch-07.webp',
    description: 'Смак з відтінками димних солодощів, червоних яблук і карамелі.'
  },
  {
    beverageId: 1003, title: 'Wild Turkey 101 0.7L',
    category: 202, volume: 0.7,
    Auchan:1049, Novus: 729, Silpo: 749, ATB:0, Rozetka: 729, 
    lastUpdated: '2024-01-01',
    inWish: false, ratings: 5, countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-101-07.webp',
    description: 'Смак ванілі, меду, карамелі, тютюну і тростинного цукру. Аромат ванілі, дуба, апельсина.'
  },
  {
    beverageId: 1004, title: 'Wild Turkey 0.7L',
    category: 202, volume: 0.7,
    Auchan:849, Novus: 589, Silpo: 599, ATB:0, Rozetka: 670,
    lastUpdated: '2024-01-01' ,
    inWish: true, ratings: 5, countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-07.webp',
    description: 'Аромат ірису, меду, карамелі і обпаленого дуба. Делікатний, солодкуватий, трохи маслянистий смак.'
  },
  {
    beverageId: 1005, title: 'Wild Turkey Rye 0.7L',
    category: 202, volume: 0.7,
    Auchan:849, Novus: 0, Silpo: 969, ATB:0, Rozetka: 1099,
    lastUpdated: '2024-01-01',
    inWish: false, ratings: 5, countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-Rye-07.webp',
    description: 'Аромат має ванільно-пряні, дубові, цитрусові акценти. У смаку грушеві тони в компанії карамелі.'
  },
  {
    beverageId: 1006, title: 'Jim Beam Double Oak 0.7L',
    category: 202, volume: 0.7,
    Auchan:1089, Novus: 1199, Silpo: 1149, ATB:0, Rozetka: 1150,
    lastUpdated: '2024-01-01',
    inWish: false, ratings: 3, countryID: 129,
    imageUrl: '/images/beverages/Jim-Beam-Double-Oak-07.webp',
    description: 'Баланс насиченого смаку і неповторного аромату.'
  },
  {
    beverageId: 1007, title: 'Jim Beam Rye 0.7L',
    category: 202, volume: 0.7,
    Auchan:0, Novus: 1179, Silpo: 1099, ATB:0, Rozetka: 1126,
    lastUpdated: '2024-01-01',
    inWish: false, ratings: 3, countryID: 129,
    imageUrl: '/images/beverages/Jim-Beam-Rye-07.webp',
    description: 'Аромат житнього хліба, чорного перцю з нотами дині, горіхів та деревної смоли. Карамельно-ванільний смак з відтінками дуба.'
  },
  {
    beverageId: 1008,
    title: 'Jim Beam White 4Y 0.7L',
    category: 202,
    volume: 0.7,
    Auchan:559,
    Novus: 549,
    Silpo: 699,
    ATB:0,
    Rozetka: 559,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 129,
    imageUrl: '/images/beverages/Jim-Beam-White-4Y-07.webp',
    description: 'Аромат з деревними тонами та відтінками лугових квітів. Смак фруктів, карамелі та ванілі.'
  },
  {
    beverageId: 1009,
	  title: 'Wild Turkey 101 1.0L',
    category: 202,
    volume: 1.0,
    Auchan:0,
    Novus: 939,
    Silpo: 0,
    ATB:0,
    Rozetka: 939,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-101-10.webp',
    description: 'Смак ванілі, меду, карамелі, тютюну і тростинного цукру. Аромат ванілі, дуба, апельсина.'
  },
  {
    beverageId: 1010,
	  title: 'Wild Turkey 1.0L',
    category: 202,
    volume: 1.0,
    Auchan:1045,
    Novus: 749,
    Silpo: 1099,
    ATB:0,
    Rozetka: 853,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 129,
    imageUrl: '/images/beverages/Wild-Turkey-10.webp',
	  description: 'Аромат ірису, меду, карамелі і обпаленого дуба. Делікатний, солодкуватий, трохи маслянистий смак.'
  },
  {
    beverageId: 1011,
	  title: 'Jim Beam Red Stag Cherry 1.0L',
    category: 202,
    volume: 1.0,
    Auchan:0,
    Novus: 1159,
    Silpo: 0,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 129,
    imageUrl: '/images/beverages/Jim-Beam-Red-Stag-Cherry-10.webp',
    description: 'Аромат черешня, ваніль, шоколад. Солодкуватий із пряним післясмаком.'
  },
  {
    beverageId: 1012,
	  title: 'Jim Beam White 4Y 1.0L',
    category: 202,
    volume: 1.0,
    Auchan:729,
    Novus: 1159,
    Silpo: 699,
    ATB:0,
    Rozetka: 699,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 129,
    imageUrl: '/images/beverages/Jim-Beam-White-4Y-07.webp',
    description: 'Аромат з деревними тонами та відтінками лугових квітів. Смак фруктів, карамелі та ванілі.'
  },
  /* --- WHISKEY --- */
  {
    beverageId: 1013,
    title: 'Jameson Stout 0.7L',
    category: 13,
    volume: 0.7,
    Auchan:795,
    Novus: 699,
    Silpo: 709,
    ATB:0,
    Rozetka: 699,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 116,
    imageUrl: '/images/beverages/Jameson-Stout-07.webp',
    description: 'Вершковий смак з нотами какао-бобів та гвоздики. Аромати смажених кавових зерен, шоколаду, зелених яблук та соковитої дині.'
  },
  {
    beverageId: 1014,
    title: 'Jameson 0.7L',
    category: 13,
    volume: 0.7,
    Auchan:599,
    Novus: 579,
    Silpo: 599,
    ATB:0,
    Rozetka: 564,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 116,
    imageUrl: '/images/beverages/jameson-07.webp',
    description: 'Купажований (Blended) смак пряний і солодкий.'
  },
  {
    beverageId: 1015,
    title: 'Ballantines Finest 0.7L',
    category: 13,
    volume: 0.7,
    Auchan:499,
    Novus: 499,
    Silpo: 499,
    ATB:0,
    Rozetka: 569,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 106,
    imageUrl: '/images/beverages/Ballantines-Finest-07.webp',
    description: 'Коричневий цукор поряд з нотами ванілі та сухофруктів. Аромат апельсинової шкірки з відтінками карамелі.'
  },
  {
    beverageId: 1016,
    title: 'Johnnie Walker Blonde 0.7L',
    category: 13,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 674,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 106,
    imageUrl: '/images/beverages/Johnnie-Walker-Blonde-07.webp',
    description: 'Аромат іриски, крем-карамелі та свіжих ягід. Смак із вершковою текстурою, ванільно-яблучними тонами.'
  },
  {
    beverageId: 1017,
    title: 'Johnnie Walker Red Label 0.7L',
    category: 13,
    volume: 0.7,
    Auchan:649,
    Novus: 499,
    Silpo: 519,
    ATB:0,
    Rozetka: 489,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 106,
    imageUrl: '/images/beverages/johnnie-walker-red-label-07.webp',
    description: 'Аромат цитрусів із нотами меду, ароматних трав, спецій. Смак чорного перцю з анісом.'
  },
  {
    beverageId: 1018,
    title: 'Hankey Bannister 0.7L',
    category: 13,
    volume: 0.7,
    Auchan:369,
    Novus: 369,
    Silpo: 369,
    ATB:362,
    Rozetka: 349,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 123,
    imageUrl: '/images/beverages/Hankey-Bannister-07.webp',
    description: 'Ванільний аромат. У фруктовому смаку відчувається мигдаль і прянощі.'
  },
  {
    beverageId: 1019,
    title: 'Jameson  1.0L',
    category: 13,
    volume: 1.0,
    Auchan:799,
    Novus: 799,
    Silpo: 799,
    ATB:0,
    Rozetka: 1090,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 116,
    imageUrl: '/images/beverages/jameson-10.webp',
    description: 'Купажований (Blended) смак пряний і солодкий.'
  },
  {
    beverageId: 1020,
    title: 'Ballantines Finest 1.0L',
    category: 13,
    volume: 1.0,
    Auchan:639,
    Novus: 629,
    Silpo: 689,
    ATB:0,
    Rozetka: 769,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 106,
    imageUrl: '/images/beverages/Ballantines-Finest-10.webp',
    description: 'Коричневий цукор поряд з нотами ванілі та сухофруктів. Аромат апельсинової шкірки з відтінками карамелі.'
  },
  {
    beverageId: 1021,
    title: 'Johnnie Walker Red Label 1.0L',
    category: 13,
    volume: 1.0,
    Auchan:779,
    Novus: 699,
    Silpo: 959,
    ATB:0,
    Rozetka: 699,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 106,
    imageUrl: '/images/beverages/johnnie-walker-red-label-10.webp',
    description: 'Аромат цитрусів із нотами меду, ароматних трав, спецій. Смак чорного перцю з анісом.'
  },
  {
    beverageId: 1022,
    title: 'Hankey Bannister 1.0L',
    category: 13,
    volume: 0.7,
    Auchan:599,
    Novus: 569,
    Silpo: 499,
    ATB:0,
    Rozetka: 499,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 123,
    imageUrl: '/images/beverages/Hankey-Bannister-10.webp',
    description: 'Ванільний аромат. У фруктовому смаку відчувається мигдаль і прянощі.'
  },
  /* --- RUM --- */
  {
    beverageId: 1023,
	  title: 'Doorlys Gold 5Y 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:934,
    Novus: 0,
    Silpo: 0,
    ATB:0,
    Rozetka: 864,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 104,
    imageUrl: '/images/beverages/Doorlys-Gold-5Y-07.webp',
    description: 'Ноти тропічних і сушених фруктів, підсмажених кокосів і дуба. Післясмак фруктовий ванільний.'
  },
  {
    beverageId: 1024,
	  title: 'Doorlys White 3Y 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:865,
    Novus: 0,
    Silpo: 0,
    ATB:0,
    Rozetka: 763,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 104,
    imageUrl: '/images/beverages/Doorlys-White-3Y-07.webp',
    description: 'Ванільний аромат із вершковими та медовими нотками. Смак з відтінками екзотичних фруктів.'
  },
  {
    beverageId: 1025,
    title: 'Botafogo Spiced 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:649,
    Novus: 0,
    Silpo: 649,
    ATB:0,
    Rozetka: 599,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 105,
    imageUrl: '/images/beverages/Botafogo-Spiced-07.webp',
    description: 'У смаку - спеції, ваніль, карамель і лакриця. Аромат солодкий цитрусовий.'
  },
  {
    beverageId: 1026,
    title: 'Appleton Reserve 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:642,
    Novus: 0,
    Silpo: 0,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 118,
    imageUrl: '/images/beverages/Appleton-Reserve-07.webp',
    description: 'Cмак пряних і горіхових нот із відтінком меду, ванілі і лісового горіха.'
  },
  {
    beverageId: 1027,
    title: 'Appleton 12Y 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:1149,
    Novus: 0,
    Silpo: 1099,
    ATB:0,
    Rozetka: 1099,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 0,
    countryID: 118,
    imageUrl: '/images/beverages/Appleton-12Y-07.webp',
    description: 'Вершковий смак із відтінками апельсинової цедри і ванілі. Аромат волоського і мускатного горіхів.'
  },
  {
    beverageId: 1028,
    title: 'Santiago de Cuba Anejo 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:599,
    Novus: 0,
    Silpo: 789,
    ATB:0,
    Rozetka: 799,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 108,
    imageUrl: '/images/beverages/Santiago-Cuba-Anejo-07.webp',
    description: 'Гладкий смак із фруктовими відтінками, нюансами вишні, ванілі, какао.'
  },
  {
    beverageId: 1029,
    title: 'Bacardi Spiced 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:452,
    Novus: 0,
    Silpo: 409,
    ATB:0,
    Rozetka: 409,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 117,
    imageUrl: '/images/beverages/Bacardi-Spiced-07.webp',
    description: 'Ваніль, кориця, мускатний горіх і мед. Аромат з нотками дубової бочки і сухофруктів.'
  },
  {
    beverageId: 1030,
    title: 'Santiago de Cuba Carta Blanca 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:399,
    Novus: 0,
    Silpo: 0,
    ATB:0,
    Rozetka: 399,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 2,
    countryID: 108,
    imageUrl: '/images/beverages/Santiago-Cuba-Carta-Blanca-07.webp',
    description: 'Квітковий аромат із відтінками меду і карамелі. Свіжий цитрусовий смак.'
  },
  {
    beverageId: 1031,
    title: 'Botafogo Black 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:649,
    Novus: 749,
    Silpo: 0,
    ATB:0,
    Rozetka: 669,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 2,
    countryID: 105,
    imageUrl: '/images/beverages/Botafogo-Black-07.webp',
    description: 'Темний ром, ваніль, апельсин, чилі. Аромат висушеного винограду.'
  },
  {
    beverageId: 1032,
    title: 'Appleton Estate Signature 0.7L',
    category: 10,
    volume: 0.7,
    Auchan:0,
    Novus: 509,
    Silpo: 509,
    ATB:0,
    Rozetka: 509,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 118,
    imageUrl: '/images/beverages/Appleton-Estate-Signature-07.webp',
    description: 'Аромат сливи та спецій із тонами сухофруктів. У смаку чорний шоколад та смажені горіхи.'
  },
  {
    beverageId: 1033,
    title: 'Bacardi Spiced 1.0L',
    category: 10,
    volume: 1.0,
    Auchan:569,
    Novus: 944,
    Silpo: 539,
    ATB:0,
    Rozetka: 539,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 117,
    imageUrl: '/images/beverages/Bacardi-Spiced-10.webp',
    description: 'Ваніль, кориця, мускатний горіх і мед. Аромат з нотками дубової бочки і сухофруктів.'
  },
  /* --- GIN --- */
  {
    beverageId: 1034,
    title: 'Malfy Pink Grapefruit 0.7L',
    category: 6,
    volume: 0.7,
    Auchan:0,
    Novus: 919,
    Silpo: 699,
    ATB:0,
    Rozetka: 860,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 117,
    imageUrl: '/images/beverages/Malfy-Pink-Grapefruit-07.webp',
    description: 'Тони сицілійського рожевого грейпфрута, коріандра та ревеня.'
  },
  {
    beverageId: 1035,
    title: 'Malfy Con Limone 0.7L',
    category: 6,
    volume: 0.7,
    Auchan:0,
    Novus: 919,
    Silpo: 699,
    ATB:0,
    Rozetka: 777,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 117,
    imageUrl: '/images/beverages/Malfy-Con-Limone-07.webp',
    description: 'Аромат з тонами лимона, ялівцю, дягелю і кориці.'
  },
  {
    beverageId: 1036,
    title: 'Gordons Pink 0.7L',
    category: 6,
    volume: 0.7,
    Auchan:0,
    Novus: 659,
    Silpo: 499,
    ATB:0,
    Rozetka: 729,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 106,
    imageUrl: '/images/beverages/Gordons-Pink-07.webp',
    description: 'Малина, полуниця та червона смородина, ялівцеві акценти.'
  },
  {
    beverageId: 1037,
    title: 'Gordons Sicilian Lemon 0.7L',
    category: 6,
    volume: 0.7,
    Auchan:529,
    Novus: 689,
    Silpo: 499,
    ATB:0,
    Rozetka: 709,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 106,
    imageUrl: '/images/beverages/Gordons-Sicilian-Lemon-07.webp',
    description: 'Аромат сицилійських лимонів із хвойними акцентами. Смак із тонами ялівцю.'
  },
  /* --- PORTWEIN --- */
  {
    beverageId: 1038,
    title: 'Colonist Башта 0.7L',
    category: 9,
    volume: 0.7,
    Auchan:564,
    Novus: 0,
    Silpo: 0,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 128,
    imageUrl: '/images/beverages/Colonist-Башта-07.webp',
    description: ''
  },
  {
    beverageId: 1039,
    title: 'Osborn Premium Rojo 0.7L',
    category: 9,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 374,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 126,
    imageUrl: '/images/beverages/Osborn-Premium-Rojo-07.webp',
    description: 'Смак з тонами полину, гіркої апельсинової шкірки та відтінками кориці.'
  },
  {
    beverageId: 1040,
    title: 'Osborn Porto Tawny 0.7L',
    category: 9,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 290,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 126,
    imageUrl: '/images/beverages/Osborn-Porto-Tawny-07.webp',
    description: 'Туріга Насьональ. Тони пряні, кондитерські.'
  },
  /* --- CHAMPAGNE --- */
  {
    beverageId: 1041,
    title: 'Colonist Бісер 0.7L',
    category: 4,
    volume: 0.7,
    Auchan:592,
    Novus: 0,
    Silpo: 0,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 128,
    imageUrl: '/images/beverages/Colonist-Бісер-07.webp',
    description: 'Аромат вершків, ванілі та хлібної скоринки. Смак зелених яблук.'
  },
  {
    beverageId: 1042,
    title: 'Martini Prosecco 0.7L',
    category: 4,
    volume: 0.7,
    Auchan:389,
    Novus: 539,
    Silpo: 369,
    ATB:0,
    Rozetka: 389,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 117,
    imageUrl: '/images/beverages/Martini-Prosecco-07.webp',
    description: 'Смак фруктових нот. Аромат зелених яблук, чебрецю, персика.'
  },
  {
    beverageId: 1043,
    title: 'Martini Rose 0.7L',
    category: 4,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 535,
    ATB:0,
    Rozetka: 438,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 117,
    imageUrl: '/images/beverages/Martini-Rose-07.webp',
    description: 'Купаж. Тони букета фруктові, квіткові.'
  },
  /* --- TEQUILA --- */
  {
    beverageId: 1044,
    title: 'Espolon Blanco 0.7L',
    category: 11,
    volume: 0.7,
    Auchan:1454,
    Novus: 0,
    Silpo: 1199,
    ATB:0,
    Rozetka: 1179,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 119,
    imageUrl: '/images/beverages/Espolon-Blanco-07.webp',
    description: 'Аромат квітковий з нотами агави та чорного перцю. Смак лайма, цедри цитрусових і печеного ананаса.'
  },
  {
    beverageId: 1045,
    title: 'Espolon Reposado 0.7L',
    category: 11,
    volume: 0.7,
    Auchan:1672,
    Novus: 0,
    Silpo: 1449,
    ATB:0,
    Rozetka: 1399,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 119,
    imageUrl: '/images/beverages/Espolon-Reposado-07.webp',
    description: 'Аромат карамелі, банана та агави. Смак тропічних плодів, квітів, карамелі та ванілі.'
  },
  {
    beverageId: 1046,
    title: 'Jose Cuervo Silver 0.7L',
    category: 11,
    volume: 0.7,
    Auchan:0,
    Novus: 579,
    Silpo: 839,
    ATB:0,
    Rozetka: 835,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 119,
    imageUrl: '/images/beverages/Jose-Cuervo-Silver-07.webp',
    description: 'Аромат карамелі та суміші трав з перцевою ноткою. Смак смаженої агави, сандалового дерева із чорним перцем.'
  },
  {
    beverageId: 1047,
    title: 'Jose Cuervo Especial 0.7L',
    category: 11,
    volume: 0.7,
    Auchan:0,
    Novus: 579,
    Silpo: 579,
    ATB:0,
    Rozetka: 850,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 119,
    imageUrl: '/images/beverages/Jose-Cuervo-Especial-07.webp',
    description: 'Аромат агави із відтінками дуба. Смак дуба та ванілі.'
  },
  /* --- TINCTURE --- */
  {
    beverageId: 1048,
    title: 'Jagermeister 0.7L',
    category: 12,
    volume: 0.7,
    Auchan:0,
    Novus: 399,
    Silpo: 399,
    ATB:476,
    Rozetka: 399,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 114,
    imageUrl: '/images/beverages/Jagermeister-07.webp',
    description: 'Смак: з легкою гіркотою, збалансований насолодою. Аромат гірських трав, лакриці, гвоздики та кориці.'
  },
  {
    beverageId: 1049,
    title: 'Becherovka 0.7L',
    category: 12,
    volume: 0.7,
    Auchan:0,
    Novus: 349,
    Silpo: 259,
    ATB:0,
    Rozetka: 349,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 109,
    imageUrl: '/images/beverages/Becherovka-07.webp',
    description: 'Понад 20 видів лікарських трав та спецій. Смак солодкий та гіркий одночасно.'
  },
  {
    beverageId: 1050,
    title: 'Jagermeister 1.0L',
    category: 12,
    volume: 1.0,
    Auchan:0,
    Novus: 919,
    Silpo: 599,
    ATB:0,
    Rozetka: 759,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 114,
    imageUrl: '/images/beverages/Jagermeister-10.webp',
    description: 'Смак: з легкою гіркотою, збалансований насолодою. Аромат гірських трав, лакриці, гвоздики та кориці.'
  },
  {
    beverageId: 1051,
    title: 'Becherovka 1.0L',
    category: 12,
    volume: 1.0,
    Auchan:0,
    Novus: 469,
    Silpo: 469,
    ATB:0,
    Rozetka: 469,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 3,
    countryID: 109,
    imageUrl: '/images/beverages/Becherovka-10.webp',
    description: 'Понад 20 видів лікарських трав та спецій. Смак солодкий та гіркий одночасно.'
  },
  /* --- HORILKA --- */
  {
    beverageId: 1052,
    title: 'Koskenkorva 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 519,
    Silpo: 319,
    ATB:0,
    Rozetka: 299,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 111,
    imageUrl: '/images/beverages/Koskenkorva-07.webp',
    description: 'Аромат з легкими ячмінними нотками. Смак із лакричними відтінками.'
  },
  {
    beverageId: 1053,
    title: 'Koskenkorva Lemon Lime 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 369,
    ATB:0,
    Rozetka: 339,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 111,
    imageUrl: '/images/beverages/Koskenkorva-Lemon-Lime-07.webp',
    description: 'Смак із нотами трав та лимону. Аромат лайма.'
  },
  {
    beverageId: 1054,
    title: 'Koskenkorva Sauna Barrel 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 499,
    Silpo: 379,
    ATB:0,
    Rozetka: 339,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 111,
    imageUrl: '/images/beverages/Koskenkorva-Sauna-Barrel-07.webp',
    description: 'Аромат із відтінками дерева, смоли та нотками диму. Присмак бурбону, смоли та диму.'
  },
  {
    beverageId: 1055,
    title: 'Absolut Mandarin 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 349,
    Silpo: 349,
    ATB:0,
    Rozetka: 369,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 127,
    imageUrl: '/images/beverages/Absolut-Mandarin-07.webp',
    description: 'Аромат мандарина. Смак апельсинової цедри.'
  },
  {
    beverageId: 1056,
    title: 'Absolut Pears 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 349,
    Silpo: 349,
    ATB:0,
    Rozetka: 369,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 127,
    imageUrl: '/images/beverages/Absolut-Pears-07.webp',
    description: 'Смак груші.'
  },
  {
    beverageId: 1057,
    title: 'Finlandia 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 424,
    Silpo: 339,
    ATB:0,
    Rozetka: 359,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 2,
    countryID: 111,
    imageUrl: '/images/beverages/Finlandia-07.webp',
    description: 'Гладкий смак від добірного ячменю.'
  },
  {
    beverageId: 1058,
    title: 'Staritsky Levitsky 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 499,
    ATB:0,
    Rozetka: 499,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 128,
    imageUrl: '/images/beverages/Staritsky-Levitsky-07.webp',
    description: 'Смак пшениці. Аромат із тонкою пряністю.'
  },
  {
    beverageId: 1059,
    title: 'Staritsky Levitsky Distil №9 0.7L',
    category: 7,
    volume: 0.7,
    Auchan:0,
    Novus: 349,
    Silpo: 389,
    ATB:0,
    Rozetka: 299,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 4,
    countryID: 128,
    imageUrl: '/images/beverages/Staritsky-Levitsky-Distil-9-07.webp',
    description: 'Смак - свіжий, натуральний. Аромат - легкий, чистий.'
  },
  {
    beverageId: 1060,
    title: 'R.Jelinek hruska 0.5L',
    category: 7,
    volume: 0.5,
    Auchan:0,
    Novus: 0,
    Silpo: 199,
    ATB:0,
    Rozetka: 0,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 2,
    countryID: 109,
    imageUrl: '/images/beverages/R.Jelinek-hruska-05.webp',
    description: 'Смак і аромат стиглої груші.'
  },
  {
    beverageId: 1061,
    title: 'Staritsky Levitsky Reserve 1.0L',
    category: 7,
    volume: 1.0,
    Auchan:0,
    Novus: 869,
    Silpo: 0,
    ATB:0,
    Rozetka: 699,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 128,
    imageUrl: '/images/beverages/Staritsky-Levitsky-Reserve-07.webp',
    description: 'Смак пшениці. Аромат із тонкою пряністю.'
  },
  {
    beverageId: 1062,
    title: 'Koskenkorva 1.0L',
    category: 7,
    volume: 1.0,
    Auchan:0,
    Novus: 0,
    Silpo: 419,
    ATB:0,
    Rozetka: 329,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 5,
    countryID: 111,
    imageUrl: '/images/beverages/Koskenkorva-10.webp',
    description: 'Аромат з легкими ячмінними нотками. Смак із лакричними відтінками.'
  },
  /* --- ABSINTHE --- */
  {
    beverageId: 1063,
    title: 'Xenta Absenta 0.7L',
    category: 201,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 749,
    ATB:0,
    Rozetka: 829,
    lastUpdated: '2024-01-01' ,
    inWish: true,
    ratings: 5,
    countryID: 117,
    imageUrl: '/images/beverages/Xenta-Absenta-07.webp',
    description: 'Смак з легким натяком на локрицю. Широка хвиля анісових ноток.'
  },
  {
    beverageId: 1064,
    title: 'R.Jelinek Absinthe 0.7L',
    category: 201,
    volume: 0.7,
    Auchan:0,
    Novus: 0,
    Silpo: 409,
    ATB:0,
    Rozetka: 365,
    lastUpdated: '2024-01-01',
    inWish: false,
    ratings: 0,
    countryID: 109,
    imageUrl: '/images/beverages/R.Jelinek-Absinthe-07.webp',
    description: 'Злегка гіркуватий смак з відтінками полину. Аромати анісу, лікарських трав, цитрусів і фенхелю.'
  },
  {
    beverageId: 1065,
    title: 'Xenta Absenta 1.0L',
    category: 201,
    volume: 1.0,
    Auchan:0,
    Novus: 1339,
    Silpo: 0,
    ATB:0,
    Rozetka: 929,
    lastUpdated: '2024-01-01',
    inWish: true,
    ratings: 5,
    countryID: 117,
    imageUrl: '/images/beverages/Xenta-Absenta-10.webp',
    description: 'Смак з легким натяком на локрицю. Широка хвиля анісових ноток.'
  },
];

module.exports = {
  countriesData, drinkCategoriesData, beveragesData,
};